### ISSUE TITLE
Not working on latest ComfyUI version 0.6.0-4

### ISSUE THREAD

**Issue by Stitch137** [ChenDarYen/ComfyUI-NAG#68]
My old Flux Kontext workflow used the NAGCFGGuider node which no longer works. I tried reinstalling ComfyUI-NAG about five or six times before I finally gave up, including deleting its folder twice. I also tried using the alternative [sd-perturbed-attention] suggested in an earlier discussion but that didn't work either. Currently I don't have a working workflow for Flux Kontext.

To be honest, I never really used the Negative prompt so maybe someone can please advise me how to put back the regular KSampler if that's a way to fix it? Thanks.

By the way, I'm testing out Qwen Image Edits which I think may be better than Flux Kontext so it may not be a great loss. I tried putting a KSampler in my Kontext workflow but the result was a crazy mess of bright colours, although I could see that Kontext was trying to create the correct image.

UPDATE: I thought editing the layers.py file as mentioned in one of the other issue threads might work as a temporary fix, however I still got the error "NAGCFGGuider.inner_sample() got an unexpected keyword argument 'latent_shapes'" when I ran my workflow.

**Comment by peepeepeepoopoopoo** [comment]
trash repo, this works perfect https://github.com/scottmudge/ComfyUI-NAG

**Comment by umpaumpa** [comment]
> trash repo, this works perfect https://github.com/scottmudge/ComfyUI-NAG

Thank u very much!
